env:
  browser: true
  es6: true
  jquery: true
  jest: true
extends: ['eslint:recommended', 'google']
rules:
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  no-unused-vars: 
    - error
    - argsIgnorePattern: '[iI]gnored'
  brace-style:
    - 0
