language: python
language: go
python:
  - "3.6"
go:
  - "1.10"
go_import_path: github.com/ucbdrive/sat
before_install:
  - sudo apt-get update
  - sudo apt-get install -y npm
  - npm install -g eslint eslint-config-google
install:
  - sudo pip install --upgrade pip
  - sudo pip install pycodestyle
  - go get github.com/aws/aws-sdk-go github.com/mitchellh/mapstructure gopkg.in/yaml.v2 github.com/satori/go.uuid
  - npm install
script:
  - pycodestyle --show-source .
  - eslint .
  - go build -i -o $GOPATH/bin/sat ./server/go
  - go test ./server/go -args --config ../../app/config/travis_config.yml
  - npm test
